version: '3.3'

services:
  db:
    image: mysql:8
    restart: always
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    env_file:
      - .env
volumes:
  snippet-db: